[mysql]
    [mysql.member]
        dsn = "root:root@tcp(127.0.0.1)/micro_member?timeout=3s&readTimeout=3s&writeTimeout=3s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
        active = 5
        idle = 5
        idleTimeout = "4h"
    [mysql.memberRead]
            dsn = "root:root@tcp(127.0.0.1)/micro_member?timeout=3s&readTimeout=3s&writeTimeout=3s&parseTime=true&loc=Local&charset=utf8,utf8mb4"
            active = 5
            idle = 5
            idleTimeout = "4h"
#[redis]